### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by streaps** [terabin/flarum-ext-sitemap#2]
The generated sitemap.xml file uses http:// in the URLs, instead of https://

Why does this happen?

**Comment by terabin** [comment]
Well, maybe a option for this is better?

**Comment by al3xLvs** [comment]
fix with this commit : https://github.com/terabin/flarum-ext-sitemap/commit/aec15e81c98c8750e7fd07b6c602de8cc9ff3b1c
